version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL="file:./dev.db"
    volumes:
      - ./prisma:/app/prisma
      - ./data:/app/data
    restart: unless-stopped

  # Optional: Add a reverse proxy for SSL and domain
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    restart: unless-stopped